services:
  rabbitmq:
    image: rabbitmq:4.2.5-management
    container_name: rabbitmq
    hostname: rabbitmq
    restart: unless-stopped

    ports:
      - "5672:5672"    # AMQP
      - "15672:15672"  # Management UI

    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
      RABBITMQ_ERLANG_COOKIE: 7eb6bd21
      RABBITMQ_DISK_FREE_LIMIT: 1073741824

    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data: