#cloud-config
users:
  - name: admin
    groups: sudo
    shell: /bin/bash
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFmPTu4BZNXVHPmRdEZGwVAzqweyE5ZTP2iixRNM1OiZ ya
package_update: true
packages:
  - curl
  - ca-certificates
  - gnupg
  - lsb-release

runcmd:
  # Docker install (Debian official method)
  - install -m 0755 -d /etc/apt/keyrings
  - curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
  - chmod a+r /etc/apt/keyrings/docker.asc
  - echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian $(. /etc/os-release && echo $VERSION_CODENAME) stable" > /etc/apt/sources.list.d/docker.list
  - apt-get update
  - apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  - groupadd docker
  - usermod -aG docker admin
  - systemctl enable docker
  - systemctl start docker

  # docker-compose_425.yml
  - |
    cat > docker-compose.yml <<EOF
    services:
      nginx:
        image: nginx:latest
        ports:
          - "80:80"

      elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
        environment:
          - discovery.type=single-node
          - xpack.security.enabled=false
          - ES_JAVA_OPTS=-Xms1g -Xmx1g
        ports:
          - "9200:9200"
    EOF

  # run stack
  - docker compose up -d